version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: hello-world-with-dc__mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./data/mysql:/var/lib/mysql
        - ./docker/mysql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_USER=hello
        - MYSQL_PASSWORD=pass
      ports:
        - "9002:3306"

    webserver:
      image: nginx:alpine
      container_name: hello-world-with-dc__webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: hello-world-with-dc__php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

